### ISSUE TITLE
gems/airbrake-api-3.1.0/lib/airbrake-api/notice.rb:4:in `<module:Airbrake>': superclass mismatch for class Notice (TypeError)

### ISSUE THREAD

**Issue by szTheory** [stve/airbrake-api#11]
Upgrading from hoptoad-api to airbrake-api. Any ideas?

```
    /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/airbrake-api-3.1.0/lib/airbrake-api/notice.rb:4:in `<module:Airbrake>': superclass mismatch for class Notice (TypeError)
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/airbrake-api-3.1.0/lib/airbrake-api/notice.rb:3:in `<top (required)>'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `block in require'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `block in load_dependency'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:596:in `new_constants_in'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `load_dependency'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/airbrake-api-3.1.0/lib/airbrake-api.rb:29:in `<top (required)>'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/bundler-1.0.18/lib/bundler/runtime.rb:68:in `require'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/bundler-1.0.18/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/bundler-1.0.18/lib/bundler/runtime.rb:66:in `each'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/bundler-1.0.18/lib/bundler/runtime.rb:66:in `block in require'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/bundler-1.0.18/lib/bundler/runtime.rb:55:in `each'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/bundler-1.0.18/lib/bundler/runtime.rb:55:in `require'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/bundler-1.0.18/lib/bundler.rb:120:in `require'
        from /Users/username/projectname2/config/application.rb:7:in `<top (required)>'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/railties-3.0.9/lib/rails/commands.rb:28:in `require'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/railties-3.0.9/lib/rails/commands.rb:28:in `block in <top (required)>'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/railties-3.0.9/lib/rails/commands.rb:27:in `tap'
        from /Users/username/.rvm/gems/ruby-1.9.2-p290@projectname/gems/railties-3.0.9/lib/rails/commands.rb:27:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

**Comment by stve** [comment]
Looks like the change from hoptoad-api to airbrake-api introduced a namespace collision with the airbrake gem.  This gem should probably not user the Airbrake namespace unless it can be completely benign.  For now it's probably best to change the namespace in airbrake-api, I'll yank the existing 3.x gems and push a new version shortly.

Thanks for reporting!

Steve

**Comment by stve** [comment]
I've release v3.2.0 which should fix the problem.  The new namespace is now AirbrakeAPI. Let me know if you have any problems.

**Comment by szTheory** [comment]
Seems to be working fine now, thanks!
